package org.lxp.dailylog.model;

import java.util.Date;

public class AccountBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private Long seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.remail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String remail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.fpemail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String fpemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.productname
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.producturl
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String producturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.joindate
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private Date joindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.seqid
     *
     * @return the value of account.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public Long getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.seqid
     *
     * @param seqid the value for account.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setSeqid(Long seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.remail
     *
     * @return the value of account.remail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getRemail() {
        return remail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.remail
     *
     * @param remail the value for account.remail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setRemail(String remail) {
        this.remail = remail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.fpemail
     *
     * @return the value of account.fpemail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getFpemail() {
        return fpemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.fpemail
     *
     * @param fpemail the value for account.fpemail
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setFpemail(String fpemail) {
        this.fpemail = fpemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.productname
     *
     * @return the value of account.productname
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.productname
     *
     * @param productname the value for account.productname
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.producturl
     *
     * @return the value of account.producturl
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getProducturl() {
        return producturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.producturl
     *
     * @param producturl the value for account.producturl
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setProducturl(String producturl) {
        this.producturl = producturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.joindate
     *
     * @return the value of account.joindate
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.joindate
     *
     * @param joindate the value for account.joindate
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.createtime
     *
     * @return the value of account.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.createtime
     *
     * @param createtime the value for account.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}