package org.lxp.dailylog.model;

import java.util.Date;

public class NavigatorBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigator.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private Long seqid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigator.name
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigator.url
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigator.title
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column navigator.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigator.seqid
     *
     * @return the value of navigator.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public Long getSeqid() {
        return seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigator.seqid
     *
     * @param seqid the value for navigator.seqid
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setSeqid(Long seqid) {
        this.seqid = seqid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigator.name
     *
     * @return the value of navigator.name
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigator.name
     *
     * @param name the value for navigator.name
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigator.url
     *
     * @return the value of navigator.url
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigator.url
     *
     * @param url the value for navigator.url
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigator.title
     *
     * @return the value of navigator.title
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigator.title
     *
     * @param title the value for navigator.title
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column navigator.createtime
     *
     * @return the value of navigator.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column navigator.createtime
     *
     * @param createtime the value for navigator.createtime
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}