package org.lxp.dailylog.service.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lxp.dailylog.model.AccountBase;
import org.lxp.dailylog.model.AccountBaseExample;

public interface AccountBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int countByExample(AccountBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int deleteByExample(AccountBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int insert(AccountBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int insertSelective(AccountBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    List<AccountBase> selectByExample(AccountBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    AccountBase selectByPrimaryKey(Long seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") AccountBase record, @Param("example") AccountBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int updateByExample(@Param("record") AccountBase record, @Param("example") AccountBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(AccountBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Sun Jul 19 19:39:54 GMT+08:00 2015
     */
    int updateByPrimaryKey(AccountBase record);
}